[unstable]
# Enable memory related functions like - memset, memcpy, memcmp; 
# which are outsourced to C by default
build-std-features = ["compiler-builtins-mem"]
# Recompile Rust core for our custom target instead of using 
# the precompiled(e.g. incompatible) libraries that ship with Rust.
build-std = ["core", "compiler_builtins"]

[build]
target = "x86_64-oxide_os.json"

# Compile our kernel with 'cargo run' and boot it in QEMU automatically
[target.'cfg(target_os = "none")']
runner = "bootimage runner"
